version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
        - ./volumes/postgres/:/var/lib/postgresql/data
    restart: on-failure

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8899"
    volumes:
      - .:/code
    ports:
      - "8899:8899"
    depends_on:
      - db
    restart: on-failure

  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    restart: on-failure

  celeryworker:
    build: .
    command: celery -A selfapp worker -l info 
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER=amqp://guest@rabbitmq:5672
    restart: on-failure
    depends_on:
      - rabbitmq
    
  celerybeat:
    build: .
    command: celery -A selfapp beat -l info 
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER=amqp://guest@rabbitmq:5672
    restart: on-failure

