version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8899:8899"
    depends_on:
      - db
    restart: on-failure

  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    restart: on-failure

  celeryworker:
    build: .
    command: celery -A selfapp worker -l info
    environment:
      - CELERY_BROKER=amqp://guest@rabbitmq:5672
    restart: on-failure
    depends_on:
      - rabbitmq
    
  celerybeat:
    build: .
    command: celery -A selfapp beat -l info
    environment:
      - CELERY_BROKER=amqp://guest@rabbitmq:5672
    restart: on-failure

